// The Veya worker protocol: the wire boundary between the Go runtime and a
// worker written in another language.
//
// This is a public contract from its first commit. Field numbers are never
// reused, fields are never removed, and a breaking change is a new package
// (veya.worker.v2) rather than an edit here.
//
// The reasoning behind the shape is in docs/worker-protocol.md. The short
// version: the client dials the runtime and opens one bidirectional stream,
// then the *server* makes requests down it and the client answers. That is
// backwards from how gRPC usually reads, and it is why a worker needs no
// inbound port, no DNS name and no certificate.
//
// What crosses this boundary is behaviour, never correctness. The claim loop,
// the lease, the fencing token and the effect ledger's reserve-commit-act
// ordering all stay on the Go side. A worker is handed a tool call that
// already has a committed ledger row behind it and an idempotency key in hand,
// and is asked only to perform it.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: veya/worker/v1/worker.proto

package workerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ProtocolVersion is the contract revision a client speaks. It is sent in
// Register so that a runtime meeting a client it does not understand says so
// at connect time instead of misreading a message later.
type ProtocolVersion int32

const (
	ProtocolVersion_PROTOCOL_VERSION_UNSPECIFIED ProtocolVersion = 0
	ProtocolVersion_PROTOCOL_VERSION_1           ProtocolVersion = 1
)

// Enum value maps for ProtocolVersion.
var (
	ProtocolVersion_name = map[int32]string{
		0: "PROTOCOL_VERSION_UNSPECIFIED",
		1: "PROTOCOL_VERSION_1",
	}
	ProtocolVersion_value = map[string]int32{
		"PROTOCOL_VERSION_UNSPECIFIED": 0,
		"PROTOCOL_VERSION_1":           1,
	}
)

func (x ProtocolVersion) Enum() *ProtocolVersion {
	p := new(ProtocolVersion)
	*p = x
	return p
}

func (x ProtocolVersion) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProtocolVersion) Descriptor() protoreflect.EnumDescriptor {
	return file_veya_worker_v1_worker_proto_enumTypes[0].Descriptor()
}

func (ProtocolVersion) Type() protoreflect.EnumType {
	return &file_veya_worker_v1_worker_proto_enumTypes[0]
}

func (x ProtocolVersion) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProtocolVersion.Descriptor instead.
func (ProtocolVersion) EnumDescriptor() ([]byte, []int) {
	return file_veya_worker_v1_worker_proto_rawDescGZIP(), []int{0}
}

// EffectClass declares what can be done about an ambiguous outcome. It mirrors
// core.EffectClass exactly; the names are spelled out rather than numbered
// loosely so that a mismatch is a compile error on both sides.
type EffectClass int32

const (
	EffectClass_EFFECT_CLASS_UNSPECIFIED       EffectClass = 0
	EffectClass_EFFECT_CLASS_NONE              EffectClass = 1
	EffectClass_EFFECT_CLASS_IDEMPOTENT_BY_KEY EffectClass = 2
	EffectClass_EFFECT_CLASS_QUERYABLE         EffectClass = 3
	EffectClass_EFFECT_CLASS_UNRECONCILABLE    EffectClass = 4
)

// Enum value maps for EffectClass.
var (
	EffectClass_name = map[int32]string{
		0: "EFFECT_CLASS_UNSPECIFIED",
		1: "EFFECT_CLASS_NONE",
		2: "EFFECT_CLASS_IDEMPOTENT_BY_KEY",
		3: "EFFECT_CLASS_QUERYABLE",
		4: "EFFECT_CLASS_UNRECONCILABLE",
	}
	EffectClass_value = map[string]int32{
		"EFFECT_CLASS_UNSPECIFIED":       0,
		"EFFECT_CLASS_NONE":              1,
		"EFFECT_CLASS_IDEMPOTENT_BY_KEY": 2,
		"EFFECT_CLASS_QUERYABLE":         3,
		"EFFECT_CLASS_UNRECONCILABLE":    4,
	}
)

func (x EffectClass) Enum() *EffectClass {
	p := new(EffectClass)
	*p = x
	return p
}

func (x EffectClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EffectClass) Descriptor() protoreflect.EnumDescriptor {
	return file_veya_worker_v1_worker_proto_enumTypes[1].Descriptor()
}

func (EffectClass) Type() protoreflect.EnumType {
	return &file_veya_worker_v1_worker_proto_enumTypes[1]
}

func (x EffectClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EffectClass.Descriptor instead.
func (EffectClass) EnumDescriptor() ([]byte, []int) {
	return file_veya_worker_v1_worker_proto_rawDescGZIP(), []int{1}
}

type JoinKind int32

const (
	JoinKind_JOIN_KIND_UNSPECIFIED JoinKind = 0
	// Wait for every child to reach a terminal state, successful or not.
	JoinKind_JOIN_KIND_ALL JoinKind = 1
	// Complete as soon as one child succeeds — or when every child has failed,
	// which is the exit that gets forgotten. A join satisfiable only by success
	// hangs forever on a bad day.
	JoinKind_JOIN_KIND_ANY JoinKind = 2
	// Complete at `quorum` successes, or as soon as too few children remain for
	// that to be possible.
	JoinKind_JOIN_KIND_QUORUM JoinKind = 3
)

// Enum value maps for JoinKind.
var (
	JoinKind_name = map[int32]string{
		0: "JOIN_KIND_UNSPECIFIED",
		1: "JOIN_KIND_ALL",
		2: "JOIN_KIND_ANY",
		3: "JOIN_KIND_QUORUM",
	}
	JoinKind_value = map[string]int32{
		"JOIN_KIND_UNSPECIFIED": 0,
		"JOIN_KIND_ALL":         1,
		"JOIN_KIND_ANY":         2,
		"JOIN_KIND_QUORUM":      3,
	}
)

func (x JoinKind) Enum() *JoinKind {
	p := new(JoinKind)
	*p = x
	return p
}

func (x JoinKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JoinKind) Descriptor() protoreflect.EnumDescriptor {
	return file_veya_worker_v1_worker_proto_enumTypes[2].Descriptor()
}

func (JoinKind) Type() protoreflect.EnumType {
	return &file_veya_worker_v1_worker_proto_enumTypes[2]
}

func (x JoinKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JoinKind.Descriptor instead.
func (JoinKind) EnumDescriptor() ([]byte, []int) {
	return file_veya_worker_v1_worker_proto_rawDescGZIP(), []int{2}
}

// DecisionKind is what the agent decided to do next.
//
// The whole Layer 5 surface is added here at once, including CANCEL and
// COMPENSATE, which the runtime does not implement yet and refuses as
// "not one this build knows". Adding an enum value later is free; renumbering
// one never is, and this contract is public from its first commit.
type DecisionKind int32

const (
	DecisionKind_DECISION_KIND_UNSPECIFIED        DecisionKind = 0
	DecisionKind_DECISION_KIND_CALL_TOOL          DecisionKind = 1
	DecisionKind_DECISION_KIND_COMPLETE           DecisionKind = 2
	DecisionKind_DECISION_KIND_FAIL               DecisionKind = 3
	DecisionKind_DECISION_KIND_CALL_TOOL_PARALLEL DecisionKind = 4
	DecisionKind_DECISION_KIND_SLEEP              DecisionKind = 5
	DecisionKind_DECISION_KIND_WAIT_FOR_SIGNAL    DecisionKind = 6
	// Reserved for Layer 6. Named now so the numbering is settled; a runtime
	// that meets one refuses it rather than misreading it as something else.
	DecisionKind_DECISION_KIND_CANCEL     DecisionKind = 7
	DecisionKind_DECISION_KIND_COMPENSATE DecisionKind = 8
)

// Enum value maps for DecisionKind.
var (
	DecisionKind_name = map[int32]string{
		0: "DECISION_KIND_UNSPECIFIED",
		1: "DECISION_KIND_CALL_TOOL",
		2: "DECISION_KIND_COMPLETE",
		3: "DECISION_KIND_FAIL",
		4: "DECISION_KIND_CALL_TOOL_PARALLEL",
		5: "DECISION_KIND_SLEEP",
		6: "DECISION_KIND_WAIT_FOR_SIGNAL",
		7: "DECISION_KIND_CANCEL",
		8: "DECISION_KIND_COMPENSATE",
	}
	DecisionKind_value = map[string]int32{
		"DECISION_KIND_UNSPECIFIED":        0,
		"DECISION_KIND_CALL_TOOL":          1,
		"DECISION_KIND_COMPLETE":           2,
		"DECISION_KIND_FAIL":               3,
		"DECISION_KIND_CALL_TOOL_PARALLEL": 4,
		"DECISION_KIND_SLEEP":              5,
		"DECISION_KIND_WAIT_FOR_SIGNAL":    6,
		"DECISION_KIND_CANCEL":             7,
		"DECISION_KIND_COMPENSATE":         8,
	}
)

func (x DecisionKind) Enum() *DecisionKind {
	p := new(DecisionKind)
	*p = x
	return p
}

func (x DecisionKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DecisionKind) Descriptor() protoreflect.EnumDescriptor {
	return file_veya_worker_v1_worker_proto_enumTypes[3].Descriptor()
}

func (DecisionKind) Type() protoreflect.EnumType {
	return &file_veya_worker_v1_worker_proto_enumTypes[3]
}

func (x DecisionKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DecisionKind.Descriptor instead.
func (DecisionKind) EnumDescriptor() ([]byte, []int) {
	return file_veya_worker_v1_worker_proto_rawDescGZIP(), []int{3}
}

// ResolutionKind is what a reconciliation attempt established.
//
// UNSPECIFIED maps to STILL_UNKNOWN, for the same reason Failure's certainty
// does: the default has to be the answer that is never wrong.
type ResolutionKind int32

const (
	ResolutionKind_RESOLUTION_KIND_UNSPECIFIED   ResolutionKind = 0
	ResolutionKind_RESOLUTION_KIND_COMMITTED     ResolutionKind = 1
	ResolutionKind_RESOLUTION_KIND_NOT_EXECUTED  ResolutionKind = 2
	ResolutionKind_RESOLUTION_KIND_STILL_UNKNOWN ResolutionKind = 3
)

// Enum value maps for ResolutionKind.
var (
	ResolutionKind_name = map[int32]string{
		0: "RESOLUTION_KIND_UNSPECIFIED",
		1: "RESOLUTION_KIND_COMMITTED",
		2: "RESOLUTION_KIND_NOT_EXECUTED",
		3: "RESOLUTION_KIND_STILL_UNKNOWN",
	}
	ResolutionKind_value = map[string]int32{
		"RESOLUTION_KIND_UNSPECIFIED":   0,
		"RESOLUTION_KIND_COMMITTED":     1,
		"RESOLUTION_KIND_NOT_EXECUTED":  2,
		"RESOLUTION_KIND_STILL_UNKNOWN": 3,
	}
)

func (x ResolutionKind) Enum() *ResolutionKind {
	p := new(ResolutionKind)
	*p = x
	return p
}

func (x ResolutionKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResolutionKind) Descriptor() protoreflect.EnumDescriptor {
	return file_veya_worker_v1_worker_proto_enumTypes[4].Descriptor()
}

func (ResolutionKind) Type() protoreflect.EnumType {
	return &file_veya_worker_v1_worker_proto_enumTypes[4]
}

func (x ResolutionKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResolutionKind.Descriptor instead.
func (ResolutionKind) EnumDescriptor() ([]byte, []int) {
	return file_veya_worker_v1_worker_proto_rawDescGZIP(), []int{4}
}

// Certainty is what a failure proves about whether the action happened.
//
// This enum is the reason Failure is a message rather than a string, and the
// zero value is the point. An error returned after a request may have been
// transmitted is not evidence that it was not transmitted: the response could
// have been lost, the connection could have dropped after the provider
// committed, the deadline could have passed while the work succeeded.
//
// So UNSPECIFIED means UNKNOWN. A client that forgets to set this field, or an
// older client that does not know the field exists, gets the pessimistic
// answer — a reconcile for what may have been a mere validation error. The
// other default would be convenient and would occasionally send a second
// refund, and there is no mechanism anywhere else in the system that would
// catch it.
type Certainty int32

const (
	// Unset. Treated as UNKNOWN.
	Certainty_CERTAINTY_UNSPECIFIED Certainty = 0
	// The action provably did not happen: the request was never transmitted.
	//
	// This is a claim, not a hint. It moves the effect to FAILED, which permits
	// a clean retry, so a worker that reports an ambiguous error this way has
	// defeated the protection the ledger provides. Use it only where the
	// failure is provably local — a payload that would not serialize, a missing
	// argument, a connection refused before anything was sent.
	Certainty_CERTAINTY_NOT_EXECUTED Certainty = 1
	// It may have happened. Say so; guessing is not an improvement.
	Certainty_CERTAINTY_UNKNOWN Certainty = 2
)

// Enum value maps for Certainty.
var (
	Certainty_name = map[int32]string{
		0: "CERTAINTY_UNSPECIFIED",
		1: "CERTAINTY_NOT_EXECUTED",
		2: "CERTAINTY_UNKNOWN",
	}
	Certainty_value = map[string]int32{
		"CERTAINTY_UNSPECIFIED":  0,
		"CERTAINTY_NOT_EXECUTED": 1,
		"CERTAINTY_UNKNOWN":      2,
	}
)

func (x Certainty) Enum() *Certainty {
	p := new(Certainty)
	*p = x
	return p
}

func (x Certainty) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Certainty) Descriptor() protoreflect.EnumDescriptor {
	return file_veya_worker_v1_worker_proto_enumTypes[5].Descriptor()
}

func (Certainty) Type() protoreflect.EnumType {
	return &file_veya_worker_v1_worker_proto_enumTypes[5]
}

func (x Certainty) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Certainty.Descriptor instead.
func (Certainty) EnumDescriptor() ([]byte, []int) {
	return file_veya_worker_v1_worker_proto_rawDescGZIP(), []int{5}
}

// ClientMessage is anything a worker sends. The first one on a stream must be
// a Register; anything else is a protocol error and closes the stream.
type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ClientMessage_Register
	//	*ClientMessage_DecideResult
	//	*ClientMessage_ExecuteResult
	//	*ClientMessage_ReconcileResult
	Message       isClientMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_veya_worker_v1_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_veya_worker_v1_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_veya_worker_v1_worker_proto_rawDescGZIP(), []int{0}
}

func (x *ClientMessage) GetMessage() isClientMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ClientMessage) GetRegister() *Register {
	if x != nil {
		if x, ok := x.Message.(*ClientMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *ClientMessage) GetDecideResult() *DecideResult {
	if x != nil {
		if x, ok := x.Message.(*ClientMessage_DecideResult); ok {
			return x.DecideResult
		}
	}
	return nil
}

func (x *ClientMessage) GetExecuteResult() *ExecuteResult {
	if x != nil {
		if x, ok := x.Message.(*ClientMessage_ExecuteResult); ok {
			return x.ExecuteResult
		}
	}
	return nil
}

func (x *ClientMessage) GetReconcileResult() *ReconcileResult {
	if x != nil {
		if x, ok := x.Message.(*ClientMessage_ReconcileResult); ok {
			return x.ReconcileResult
		}
	}
	return nil
}

type isClientMessage_Message interface {
	isClientMessage_Message()
}

type ClientMessage_Register struct {
	Register *Register `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type ClientMessage_DecideResult struct {
	DecideResult *DecideResult `protobuf:"bytes,2,opt,name=decide_result,json=decideResult,proto3,oneof"`
}

type ClientMessage_ExecuteResult struct {
	ExecuteResult *ExecuteResult `protobuf:"bytes,3,opt,name=execute_result,json=executeResult,proto3,oneof"`
}

type ClientMessage_ReconcileResult struct {
	ReconcileResult *ReconcileResult `protobuf:"bytes,4,opt,name=reconcile_result,json=reconcileResult,proto3,oneof"`
}

func (*ClientMessage_Register) isClientMessage_Message() {}

func (*ClientMessage_DecideResult) isClientMessage_Message() {}

func (*ClientMessage_ExecuteResult) isClientMessage_Message() {}

func (*ClientMessage_ReconcileResult) isClientMessage_Message() {}

// ServerMessage is anything the runtime sends. Requests are concurrent: the
// runtime does not wait for one result before sending the next request, so a
// worker must be able to have several in flight.
type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ServerMessage_Registered
	//	*ServerMessage_Decide
	//	*ServerMessage_Execute
	//	*ServerMessage_Reconcile
	Message       isServerMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_veya_worker_v1_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_veya_worker_v1_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_veya_worker_v1_worker_proto_rawDescGZIP(), []int{1}
}

func (x *ServerMessage) GetMessage() isServerMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ServerMessage) GetRegistered() *Registered {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_Registered); ok {
			return x.Registered
		}
	}
	return nil
}

func (x *ServerMessage) GetDecide() *DecideRequest {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_Decide); ok {
			return x.Decide
		}
	}
	return nil
}

func (x *ServerMessage) GetExecute() *ExecuteRequest {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_Execute); ok {
			return x.Execute
		}
	}
	return nil
}

func (x *ServerMessage) GetReconcile() *ReconcileRequest {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_Reconcile); ok {
			return x.Reconcile
		}
	}
	return nil
}

type isServerMessage_Message interface {
	isServerMessage_Message()
}

type ServerMessage_Registered struct {
	Registered *Registered `protobuf:"bytes,1,opt,name=registered,proto3,oneof"`
}

type ServerMessage_Decide struct {
	Decide *DecideRequest `protobuf:"bytes,2,opt,name=decide,proto3,oneof"`
}

type ServerMessage_Execute struct {
	Execute *ExecuteRequest `protobuf:"bytes,3,opt,name=execute,proto3,oneof"`
}

type ServerMessage_Reconcile struct {
	Reconcile *ReconcileRequest `protobuf:"bytes,4,opt,name=reconcile,proto3,oneof"`
}

func (*ServerMessage_Registered) isServerMessage_Message() {}

func (*ServerMessage_Decide) isServerMessage_Message() {}

func (*ServerMessage_Execute) isServerMessage_Message() {}

func (*ServerMessage_Reconcile) isServerMessage_Message() {}

// Register declares which agent this worker serves and what it can run.
//
// It is the only place a tool's effect class is ever stated. The runtime holds
// no second copy to drift from, which is the answer to "two languages holding
// the same agent definition" — only one of them holds it.
type Register struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion ProtocolVersion        `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3,enum=veya.worker.v1.ProtocolVersion" json:"protocol_version,omitempty"`
	// Agent name and version. The version is compared against the version
	// pinned on a run at start: a worker on v2 is refused the chance to decide
	// for a run pinned to v1, because its body may have different steps and
	// replay would diverge silently.
	AgentName    string `protobuf:"bytes,2,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	AgentVersion string `protobuf:"bytes,3,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	// WorkerId identifies this process. It appears in runtime logs, so a tool
	// call can be traced back to the process that ran it.
	WorkerId string `protobuf:"bytes,4,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	// Runtime describes the client for operators: "python 3.13.5", "go 1.26".
	// Nothing branches on it.
	Runtime string            `protobuf:"bytes,5,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Tools   []*ToolDescriptor `protobuf:"bytes,6,rep,name=tools,proto3" json:"tools,omitempty"`
	// Decides is false for a worker that hosts tools but has no agent body —
	// a tool-only process. Such a worker is never sent a DecideRequest.
	Decides       bool `protobuf:"varint,7,opt,name=decides,proto3" json:"decides,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Register) Reset() {
	*x = Register{}
	mi := &file_veya_worker_v1_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register) ProtoMessage() {}

func (x *Register) ProtoReflect() protoreflect.Message {
	mi := &file_veya_worker_v1_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register.ProtoReflect.Descriptor instead.
func (*Register) Descriptor() ([]byte, []int) {
	return file_veya_worker_v1_worker_proto_rawDescGZIP(), []int{2}
}

func (x *Register) GetProtocolVersion() ProtocolVersion {
	if x != nil {
		return x.ProtocolVersion
	}
	return ProtocolVersion_PROTOCOL_VERSION_UNSPECIFIED
}

func (x *Register) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *Register) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *Register) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *Register) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *Register) GetTools() []*ToolDescriptor {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *Register) GetDecides() bool {
	if x != nil {
		return x.Decides
	}
	return false
}

// Registered confirms the session. A runtime that cannot accept the
// registration closes the stream with a gRPC status instead of sending this,
// so a client that receives it is fully in service.
type Registered struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RuntimeVersion string                 `protobuf:"bytes,2,opt,name=runtime_version,json=runtimeVersion,proto3" json:"runtime_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Registered) Reset() {
	*x = Registered{}
	mi := &file_veya_worker_v1_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Registered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registered) ProtoMessage() {}

func (x *Registered) ProtoReflect() protoreflect.Message {
	mi := &file_veya_worker_v1_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registered.ProtoReflect.Descriptor instead.
func (*Registered) Descriptor() ([]byte, []int) {
	return file_veya_worker_v1_worker_proto_rawDescGZIP(), []int{3}
}

func (x *Registered) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Registered) GetRuntimeVersion() string {
	if x != nil {
		return x.RuntimeVersion
	}
	return ""
}

// ToolDescriptor is everything the runtime needs to know about one tool.
//
// It mirrors core.ToolDescriptor minus the handler, which is the thing that
// stays on the client side and is the whole reason the protocol exists.
type ToolDescriptor struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	EffectClass EffectClass            `protobuf:"varint,2,opt,name=effect_class,json=effectClass,proto3,enum=veya.worker.v1.EffectClass" json:"effect_class,omitempty"`
	// KeyTtlSeconds is how long the provider actually honours an idempotency
	// key. Zero means no expiry is claimed, which is only honest for a provider
	// documenting indefinite retention. Past this window an unresolved effect
	// escalates rather than reconciling, because "not found" from a provider
	// that has forgotten the key is not evidence that nothing happened.
	KeyTtlSeconds int64 `protobuf:"varint,3,opt,name=key_ttl_seconds,json=keyTtlSeconds,proto3" json:"key_ttl_seconds,omitempty"`
	// Reconcilable reports whether the client registered a reconcile hook.
	// A QUERYABLE tool without one is rejected at registration: a tool that
	// cannot be asked what it did is UNRECONCILABLE, whatever it calls itself.
	Reconcilable  bool `protobuf:"varint,4,opt,name=reconcilable,proto3" json:"reconcilable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolDescriptor) Reset() {
	*x = ToolDescriptor{}
	mi := &file_veya_worker_v1_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolDescriptor) ProtoMessage() {}

func (x *ToolDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_veya_worker_v1_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolDescriptor.ProtoReflect.Descriptor instead.
func (*ToolDescriptor) Descriptor() ([]byte, []int) {
	return file_veya_worker_v1_worker_proto_rawDescGZIP(), []int{4}
}

func (x *ToolDescriptor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolDescriptor) GetEffectClass() EffectClass {
	if x != nil {
		return x.EffectClass
	}
	return EffectClass_EFFECT_CLASS_UNSPECIFIED
}

func (x *ToolDescriptor) GetKeyTtlSeconds() int64 {
	if x != nil {
		return x.KeyTtlSeconds
	}
	return 0
}

func (x *ToolDescriptor) GetReconcilable() bool {
	if x != nil {
		return x.Reconcilable
	}
	return false
}

// DecideRequest asks "what does this run owe next?", with the history that
// answers it.
//
// History is sent whole rather than incrementally. It is the authoritative
// input to replay, and a client assembling it from deltas would be holding
// state across requests — which is exactly the thing that forks a run when the
// client restarts and its state does not.
type DecideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Run           *Run                   `protobuf:"bytes,2,opt,name=run,proto3" json:"run,omitempty"`
	History       []*Event               `protobuf:"bytes,3,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecideRequest) Reset() {
	*x = DecideRequest{}
	mi := &file_veya_worker_v1_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecideRequest) ProtoMessage() {}

func (x *DecideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_veya_worker_v1_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecideRequest.ProtoReflect.Descriptor instead.
func (*DecideRequest) Descriptor() ([]byte, []int) {
	return file_veya_worker_v1_worker_proto_rawDescGZIP(), []int{5}
}

func (x *DecideRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *DecideRequest) GetRun() *Run {
	if x != nil {
		return x.Run
	}
	return nil
}

func (x *DecideRequest) GetHistory() []*Event {
	if x != nil {
		return x.History
	}
	return nil
}

// DecideResult answers one DecideRequest. A failure here fails the run: a
// decider that cannot decide leaves a run nobody will ever advance, and
// invisible stalled work is worse than a recorded failure.
type DecideResult struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	CallId string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	// Types that are valid to be assigned to Outcome:
	//
	//	*DecideResult_Decision
	//	*DecideResult_Failure
	Outcome       isDecideResult_Outcome `protobuf_oneof:"outcome"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecideResult) Reset() {
	*x = DecideResult{}
	mi := &file_veya_worker_v1_worker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecideResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecideResult) ProtoMessage() {}

func (x *DecideResult) ProtoReflect() protoreflect.Message {
	mi := &file_veya_worker_v1_worker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecideResult.ProtoReflect.Descriptor instead.
func (*DecideResult) Descriptor() ([]byte, []int) {
	return file_veya_worker_v1_worker_proto_rawDescGZIP(), []int{6}
}

func (x *DecideResult) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *DecideResult) GetOutcome() isDecideResult_Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

func (x *DecideResult) GetDecision() *Decision {
	if x != nil {
		if x, ok := x.Outcome.(*DecideResult_Decision); ok {
			return x.Decision
		}
	}
	return nil
}

func (x *DecideResult) GetFailure() *Failure {
	if x != nil {
		if x, ok := x.Outcome.(*DecideResult_Failure); ok {
			return x.Failure
		}
	}
	return nil
}

type isDecideResult_Outcome interface {
	isDecideResult_Outcome()
}

type DecideResult_Decision struct {
	Decision *Decision `protobuf:"bytes,2,opt,name=decision,proto3,oneof"`
}

type DecideResult_Failure struct {
	Failure *Failure `protobuf:"bytes,3,opt,name=failure,proto3,oneof"`
}

func (*DecideResult_Decision) isDecideResult_Outcome() {}

func (*DecideResult_Failure) isDecideResult_Outcome() {}

type Decision struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Kind  DecisionKind           `protobuf:"varint,1,opt,name=kind,proto3,enum=veya.worker.v1.DecisionKind" json:"kind,omitempty"`
	// Set when kind is CALL_TOOL, and when kind is CALL_TOOL_PARALLEL — where
	// it is the *parent* step, and the children are numbered from it.
	//
	// StepId is a run-relative logical position assigned by invocation order,
	// never completion order — it is what the idempotency key is derived from,
	// so it has to survive retries, reassignment and replay.
	StepId  string `protobuf:"bytes,2,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	Tool    string `protobuf:"bytes,3,opt,name=tool,proto3" json:"tool,omitempty"`
	Payload []byte `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	// Set when kind is COMPLETE.
	Output []byte `protobuf:"bytes,5,opt,name=output,proto3" json:"output,omitempty"`
	// Set when kind is FAIL.
	Error string `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	// Set when kind is CALL_TOOL_PARALLEL.
	//
	// Repeated ToolCall inside one Decision, rather than repeated Decision.
	// The other encoding is the obvious one and it permits nonsense: a sleep
	// and a cancel in the same batch, two completes, a complete followed by a
	// call. Every one of those would have to be rejected at runtime, in Go,
	// with an error message the Python SDK then has to take care never to
	// provoke. This shape makes them unrepresentable instead.
	//
	// Order is invocation order and is load-bearing: children are named from
	// their position here. See docs/execution-model.md section 7.1.
	Calls []*ToolCall `protobuf:"bytes,7,rep,name=calls,proto3" json:"calls,omitempty"`
	Join  *JoinPolicy `protobuf:"bytes,8,opt,name=join,proto3" json:"join,omitempty"`
	// Set when kind is SLEEP: the instant to wake at.
	WakeAtUnixNano int64 `protobuf:"varint,9,opt,name=wake_at_unix_nano,json=wakeAtUnixNano,proto3" json:"wake_at_unix_nano,omitempty"`
	// Set when kind is WAIT_FOR_SIGNAL.
	Signal        *SignalWait `protobuf:"bytes,10,opt,name=signal,proto3" json:"signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Decision) Reset() {
	*x = Decision{}
	mi := &file_veya_worker_v1_worker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Decision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decision) ProtoMessage() {}

func (x *Decision) ProtoReflect() protoreflect.Message {
	mi := &file_veya_worker_v1_worker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decision.ProtoReflect.Descriptor instead.
func (*Decision) Descriptor() ([]byte, []int) {
	return file_veya_worker_v1_worker_proto_rawDescGZIP(), []int{7}
}

func (x *Decision) GetKind() DecisionKind {
	if x != nil {
		return x.Kind
	}
	return DecisionKind_DECISION_KIND_UNSPECIFIED
}

func (x *Decision) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *Decision) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *Decision) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Decision) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *Decision) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Decision) GetCalls() []*ToolCall {
	if x != nil {
		return x.Calls
	}
	return nil
}

func (x *Decision) GetJoin() *JoinPolicy {
	if x != nil {
		return x.Join
	}
	return nil
}

func (x *Decision) GetWakeAtUnixNano() int64 {
	if x != nil {
		return x.WakeAtUnixNano
	}
	return 0
}

func (x *Decision) GetSignal() *SignalWait {
	if x != nil {
		return x.Signal
	}
	return nil
}

// ToolCall is one invocation inside a parallel decision.
//
// It carries no step id. The runtime numbers children parent.Child(i) from
// their position in the calls list, so the naming rule has one definition
// rather than one per client — and a client cannot accidentally give two
// children the same key.
type ToolCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tool          string                 `protobuf:"bytes,1,opt,name=tool,proto3" json:"tool,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_veya_worker_v1_worker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_veya_worker_v1_worker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_veya_worker_v1_worker_proto_rawDescGZIP(), []int{8}
}

func (x *ToolCall) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *ToolCall) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// JoinPolicy states when a fan-out has finished waiting.
//
// It never states what a partial failure *means*. Every outcome goes back to
// the agent body in invocation order, successes and failures alike, and the
// body decides — the runtime knows about effects and nothing about meaning.
type JoinPolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Kind  JoinKind               `protobuf:"varint,1,opt,name=kind,proto3,enum=veya.worker.v1.JoinKind" json:"kind,omitempty"`
	// Quorum is how many successes JOIN_KIND_QUORUM needs. Ignored otherwise.
	// A quorum larger than the fan-out is refused: it is unsatisfiable from the
	// first instant, so it would park the run forever with nothing in the logs
	// pointing at the cause.
	Quorum        int32 `protobuf:"varint,2,opt,name=quorum,proto3" json:"quorum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinPolicy) Reset() {
	*x = JoinPolicy{}
	mi := &file_veya_worker_v1_worker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinPolicy) ProtoMessage() {}

func (x *JoinPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_veya_worker_v1_worker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinPolicy.ProtoReflect.Descriptor instead.
func (*JoinPolicy) Descriptor() ([]byte, []int) {
	return file_veya_worker_v1_worker_proto_rawDescGZIP(), []int{9}
}

func (x *JoinPolicy) GetKind() JoinKind {
	if x != nil {
		return x.Kind
	}
	return JoinKind_JOIN_KIND_UNSPECIFIED
}

func (x *JoinPolicy) GetQuorum() int32 {
	if x != nil {
		return x.Quorum
	}
	return 0
}

// SignalWait is a run asking to be woken when something outside the system
// happens.
//
// The wait is a read, not a delivery. A signal that arrived before the run got
// here is already stored, so early and late arrival run identical code and the
// early-signal race does not exist — see docs/execution-model.md section 4.
type SignalWait struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// DeadlineUnixNano bounds the wait. Zero waits indefinitely, which is
	// honest for a human approval and dangerous for anything automated.
	DeadlineUnixNano int64 `protobuf:"varint,2,opt,name=deadline_unix_nano,json=deadlineUnixNano,proto3" json:"deadline_unix_nano,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SignalWait) Reset() {
	*x = SignalWait{}
	mi := &file_veya_worker_v1_worker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalWait) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalWait) ProtoMessage() {}

func (x *SignalWait) ProtoReflect() protoreflect.Message {
	mi := &file_veya_worker_v1_worker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalWait.ProtoReflect.Descriptor instead.
func (*SignalWait) Descriptor() ([]byte, []int) {
	return file_veya_worker_v1_worker_proto_rawDescGZIP(), []int{10}
}

func (x *SignalWait) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SignalWait) GetDeadlineUnixNano() int64 {
	if x != nil {
		return x.DeadlineUnixNano
	}
	return 0
}

// Run is the durable state of one agent execution.
type Run struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	AgentName     string                 `protobuf:"bytes,2,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,3,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Input         []byte                 `protobuf:"bytes,5,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Run) Reset() {
	*x = Run{}
	mi := &file_veya_worker_v1_worker_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Run) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Run) ProtoMessage() {}

func (x *Run) ProtoReflect() protoreflect.Message {
	mi := &file_veya_worker_v1_worker_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Run.ProtoReflect.Descriptor instead.
func (*Run) Descriptor() ([]byte, []int) {
	return file_veya_worker_v1_worker_proto_rawDescGZIP(), []int{11}
}

func (x *Run) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *Run) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *Run) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *Run) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Run) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

// Event is one immutable fact in a run's history.
type Event struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	RunId  string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Seq    int64                  `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Type   string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	StepId string                 `protobuf:"bytes,4,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	// Payload is the versioned envelope exactly as stored: {"v":1,"data":{...}}.
	// It crosses the wire verbatim so that a client reading history sees what
	// the database holds, byte for byte, and an envelope version the client does
	// not understand is the client's error to raise rather than something the
	// runtime silently reshapes.
	Payload           []byte `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	CreatedAtUnixNano int64  `protobuf:"varint,6,opt,name=created_at_unix_nano,json=createdAtUnixNano,proto3" json:"created_at_unix_nano,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_veya_worker_v1_worker_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_veya_worker_v1_worker_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_veya_worker_v1_worker_proto_rawDescGZIP(), []int{12}
}

func (x *Event) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *Event) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *Event) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetCreatedAtUnixNano() int64 {
	if x != nil {
		return x.CreatedAtUnixNano
	}
	return 0
}

// ExecuteRequest is one tool call. Everything needed to perform it is here;
// the worker holds no state between calls.
type ExecuteRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	CallId string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Tool   string                 `protobuf:"bytes,2,opt,name=tool,proto3" json:"tool,omitempty"`
	RunId  string                 `protobuf:"bytes,3,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	TaskId string                 `protobuf:"bytes,4,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	StepId string                 `protobuf:"bytes,5,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	// IdempotencyKey is stable across every retry, reassignment and replay of
	// this logical step, and is the thing to hand the provider as its
	// Idempotency-Key header or equivalent.
	//
	// Empty for a NONE-class tool, which has no ledger row and nothing to
	// deduplicate. For every other class it is not a convenience: a tool
	// declaring IDEMPOTENT_BY_KEY cannot make that claim true without it.
	IdempotencyKey string `protobuf:"bytes,6,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Payload        []byte `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`
	// Attempt is which try this is, starting at 1. For logging, and for a tool
	// that wants to reason about its own retries. Nothing about correctness
	// depends on it.
	Attempt       int32 `protobuf:"varint,8,opt,name=attempt,proto3" json:"attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_veya_worker_v1_worker_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_veya_worker_v1_worker_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_veya_worker_v1_worker_proto_rawDescGZIP(), []int{13}
}

func (x *ExecuteRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ExecuteRequest) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *ExecuteRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ExecuteRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ExecuteRequest) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *ExecuteRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *ExecuteRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExecuteRequest) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

type ExecuteResult struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	CallId string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	// Types that are valid to be assigned to Outcome:
	//
	//	*ExecuteResult_Result
	//	*ExecuteResult_Failure
	Outcome       isExecuteResult_Outcome `protobuf_oneof:"outcome"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResult) Reset() {
	*x = ExecuteResult{}
	mi := &file_veya_worker_v1_worker_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResult) ProtoMessage() {}

func (x *ExecuteResult) ProtoReflect() protoreflect.Message {
	mi := &file_veya_worker_v1_worker_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResult.ProtoReflect.Descriptor instead.
func (*ExecuteResult) Descriptor() ([]byte, []int) {
	return file_veya_worker_v1_worker_proto_rawDescGZIP(), []int{14}
}

func (x *ExecuteResult) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ExecuteResult) GetOutcome() isExecuteResult_Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

func (x *ExecuteResult) GetResult() []byte {
	if x != nil {
		if x, ok := x.Outcome.(*ExecuteResult_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *ExecuteResult) GetFailure() *Failure {
	if x != nil {
		if x, ok := x.Outcome.(*ExecuteResult_Failure); ok {
			return x.Failure
		}
	}
	return nil
}

type isExecuteResult_Outcome interface {
	isExecuteResult_Outcome()
}

type ExecuteResult_Result struct {
	// Result is opaque JSON. The runtime never interprets it, beyond looking
	// for a conventional reference field to record as the provider's own
	// identifier.
	Result []byte `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

type ExecuteResult_Failure struct {
	Failure *Failure `protobuf:"bytes,3,opt,name=failure,proto3,oneof"`
}

func (*ExecuteResult_Result) isExecuteResult_Outcome() {}

func (*ExecuteResult_Failure) isExecuteResult_Outcome() {}

// ReconcileRequest asks the provider, through the worker, whether an action
// under this key actually happened.
//
// A reconcile hook must not perform the action. One that executes rather than
// queries turns the reconciliation of an already-committed effect into the
// duplicate the ledger exists to prevent.
type ReconcileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Tool          string                 `protobuf:"bytes,2,opt,name=tool,proto3" json:"tool,omitempty"`
	Effect        *Effect                `protobuf:"bytes,3,opt,name=effect,proto3" json:"effect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconcileRequest) Reset() {
	*x = ReconcileRequest{}
	mi := &file_veya_worker_v1_worker_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileRequest) ProtoMessage() {}

func (x *ReconcileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_veya_worker_v1_worker_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileRequest.ProtoReflect.Descriptor instead.
func (*ReconcileRequest) Descriptor() ([]byte, []int) {
	return file_veya_worker_v1_worker_proto_rawDescGZIP(), []int{15}
}

func (x *ReconcileRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ReconcileRequest) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *ReconcileRequest) GetEffect() *Effect {
	if x != nil {
		return x.Effect
	}
	return nil
}

type ReconcileResult struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	CallId string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	// Types that are valid to be assigned to Outcome:
	//
	//	*ReconcileResult_Resolution
	//	*ReconcileResult_Failure
	Outcome       isReconcileResult_Outcome `protobuf_oneof:"outcome"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconcileResult) Reset() {
	*x = ReconcileResult{}
	mi := &file_veya_worker_v1_worker_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileResult) ProtoMessage() {}

func (x *ReconcileResult) ProtoReflect() protoreflect.Message {
	mi := &file_veya_worker_v1_worker_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileResult.ProtoReflect.Descriptor instead.
func (*ReconcileResult) Descriptor() ([]byte, []int) {
	return file_veya_worker_v1_worker_proto_rawDescGZIP(), []int{16}
}

func (x *ReconcileResult) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ReconcileResult) GetOutcome() isReconcileResult_Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

func (x *ReconcileResult) GetResolution() *Resolution {
	if x != nil {
		if x, ok := x.Outcome.(*ReconcileResult_Resolution); ok {
			return x.Resolution
		}
	}
	return nil
}

func (x *ReconcileResult) GetFailure() *Failure {
	if x != nil {
		if x, ok := x.Outcome.(*ReconcileResult_Failure); ok {
			return x.Failure
		}
	}
	return nil
}

type isReconcileResult_Outcome interface {
	isReconcileResult_Outcome()
}

type ReconcileResult_Resolution struct {
	Resolution *Resolution `protobuf:"bytes,2,opt,name=resolution,proto3,oneof"`
}

type ReconcileResult_Failure struct {
	Failure *Failure `protobuf:"bytes,3,opt,name=failure,proto3,oneof"`
}

func (*ReconcileResult_Resolution) isReconcileResult_Outcome() {}

func (*ReconcileResult_Failure) isReconcileResult_Outcome() {}

type Resolution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          ResolutionKind         `protobuf:"varint,1,opt,name=kind,proto3,enum=veya.worker.v1.ResolutionKind" json:"kind,omitempty"`
	Response      []byte                 `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	ExternalRef   string                 `protobuf:"bytes,3,opt,name=external_ref,json=externalRef,proto3" json:"external_ref,omitempty"`
	Detail        string                 `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resolution) Reset() {
	*x = Resolution{}
	mi := &file_veya_worker_v1_worker_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resolution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resolution) ProtoMessage() {}

func (x *Resolution) ProtoReflect() protoreflect.Message {
	mi := &file_veya_worker_v1_worker_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resolution.ProtoReflect.Descriptor instead.
func (*Resolution) Descriptor() ([]byte, []int) {
	return file_veya_worker_v1_worker_proto_rawDescGZIP(), []int{17}
}

func (x *Resolution) GetKind() ResolutionKind {
	if x != nil {
		return x.Kind
	}
	return ResolutionKind_RESOLUTION_KIND_UNSPECIFIED
}

func (x *Resolution) GetResponse() []byte {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *Resolution) GetExternalRef() string {
	if x != nil {
		return x.ExternalRef
	}
	return ""
}

func (x *Resolution) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

// Effect is a ledger row, as the reconcile hook needs to see it.
type Effect struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	EffectId          string                 `protobuf:"bytes,1,opt,name=effect_id,json=effectId,proto3" json:"effect_id,omitempty"`
	RunId             string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	TaskId            string                 `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	EffectType        string                 `protobuf:"bytes,4,opt,name=effect_type,json=effectType,proto3" json:"effect_type,omitempty"`
	EffectClass       EffectClass            `protobuf:"varint,5,opt,name=effect_class,json=effectClass,proto3,enum=veya.worker.v1.EffectClass" json:"effect_class,omitempty"`
	IdempotencyKey    string                 `protobuf:"bytes,6,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Status            string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	ExternalRef       string                 `protobuf:"bytes,8,opt,name=external_ref,json=externalRef,proto3" json:"external_ref,omitempty"`
	Request           []byte                 `protobuf:"bytes,9,opt,name=request,proto3" json:"request,omitempty"`
	Response          []byte                 `protobuf:"bytes,10,opt,name=response,proto3" json:"response,omitempty"`
	CreatedAtUnixNano int64                  `protobuf:"varint,11,opt,name=created_at_unix_nano,json=createdAtUnixNano,proto3" json:"created_at_unix_nano,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Effect) Reset() {
	*x = Effect{}
	mi := &file_veya_worker_v1_worker_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Effect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Effect) ProtoMessage() {}

func (x *Effect) ProtoReflect() protoreflect.Message {
	mi := &file_veya_worker_v1_worker_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Effect.ProtoReflect.Descriptor instead.
func (*Effect) Descriptor() ([]byte, []int) {
	return file_veya_worker_v1_worker_proto_rawDescGZIP(), []int{18}
}

func (x *Effect) GetEffectId() string {
	if x != nil {
		return x.EffectId
	}
	return ""
}

func (x *Effect) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *Effect) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Effect) GetEffectType() string {
	if x != nil {
		return x.EffectType
	}
	return ""
}

func (x *Effect) GetEffectClass() EffectClass {
	if x != nil {
		return x.EffectClass
	}
	return EffectClass_EFFECT_CLASS_UNSPECIFIED
}

func (x *Effect) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *Effect) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Effect) GetExternalRef() string {
	if x != nil {
		return x.ExternalRef
	}
	return ""
}

func (x *Effect) GetRequest() []byte {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *Effect) GetResponse() []byte {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *Effect) GetCreatedAtUnixNano() int64 {
	if x != nil {
		return x.CreatedAtUnixNano
	}
	return 0
}

// Failure is how a worker reports that something went wrong, and it carries
// the single most important bit in this protocol.
type Failure struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Message is what went wrong, in words.
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// Type is the client-side error class, e.g. a Python exception name. For
	// operators reading logs; nothing branches on it.
	Type          string    `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Certainty     Certainty `protobuf:"varint,3,opt,name=certainty,proto3,enum=veya.worker.v1.Certainty" json:"certainty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Failure) Reset() {
	*x = Failure{}
	mi := &file_veya_worker_v1_worker_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Failure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Failure) ProtoMessage() {}

func (x *Failure) ProtoReflect() protoreflect.Message {
	mi := &file_veya_worker_v1_worker_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Failure.ProtoReflect.Descriptor instead.
func (*Failure) Descriptor() ([]byte, []int) {
	return file_veya_worker_v1_worker_proto_rawDescGZIP(), []int{19}
}

func (x *Failure) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Failure) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Failure) GetCertainty() Certainty {
	if x != nil {
		return x.Certainty
	}
	return Certainty_CERTAINTY_UNSPECIFIED
}

var File_veya_worker_v1_worker_proto protoreflect.FileDescriptor

const file_veya_worker_v1_worker_proto_rawDesc = "" +
	"\n" +
	"\x1bveya/worker/v1/worker.proto\x12\x0eveya.worker.v1\"\xad\x02\n" +
	"\rClientMessage\x126\n" +
	"\bregister\x18\x01 \x01(\v2\x18.veya.worker.v1.RegisterH\x00R\bregister\x12C\n" +
	"\rdecide_result\x18\x02 \x01(\v2\x1c.veya.worker.v1.DecideResultH\x00R\fdecideResult\x12F\n" +
	"\x0eexecute_result\x18\x03 \x01(\v2\x1d.veya.worker.v1.ExecuteResultH\x00R\rexecuteResult\x12L\n" +
	"\x10reconcile_result\x18\x04 \x01(\v2\x1f.veya.worker.v1.ReconcileResultH\x00R\x0freconcileResultB\t\n" +
	"\amessage\"\x8f\x02\n" +
	"\rServerMessage\x12<\n" +
	"\n" +
	"registered\x18\x01 \x01(\v2\x1a.veya.worker.v1.RegisteredH\x00R\n" +
	"registered\x127\n" +
	"\x06decide\x18\x02 \x01(\v2\x1d.veya.worker.v1.DecideRequestH\x00R\x06decide\x12:\n" +
	"\aexecute\x18\x03 \x01(\v2\x1e.veya.worker.v1.ExecuteRequestH\x00R\aexecute\x12@\n" +
	"\treconcile\x18\x04 \x01(\v2 .veya.worker.v1.ReconcileRequestH\x00R\treconcileB\t\n" +
	"\amessage\"\xa1\x02\n" +
	"\bRegister\x12J\n" +
	"\x10protocol_version\x18\x01 \x01(\x0e2\x1f.veya.worker.v1.ProtocolVersionR\x0fprotocolVersion\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x02 \x01(\tR\tagentName\x12#\n" +
	"\ragent_version\x18\x03 \x01(\tR\fagentVersion\x12\x1b\n" +
	"\tworker_id\x18\x04 \x01(\tR\bworkerId\x12\x18\n" +
	"\aruntime\x18\x05 \x01(\tR\aruntime\x124\n" +
	"\x05tools\x18\x06 \x03(\v2\x1e.veya.worker.v1.ToolDescriptorR\x05tools\x12\x18\n" +
	"\adecides\x18\a \x01(\bR\adecides\"T\n" +
	"\n" +
	"Registered\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12'\n" +
	"\x0fruntime_version\x18\x02 \x01(\tR\x0eruntimeVersion\"\xb0\x01\n" +
	"\x0eToolDescriptor\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12>\n" +
	"\feffect_class\x18\x02 \x01(\x0e2\x1b.veya.worker.v1.EffectClassR\veffectClass\x12&\n" +
	"\x0fkey_ttl_seconds\x18\x03 \x01(\x03R\rkeyTtlSeconds\x12\"\n" +
	"\freconcilable\x18\x04 \x01(\bR\freconcilable\"\x80\x01\n" +
	"\rDecideRequest\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12%\n" +
	"\x03run\x18\x02 \x01(\v2\x13.veya.worker.v1.RunR\x03run\x12/\n" +
	"\ahistory\x18\x03 \x03(\v2\x15.veya.worker.v1.EventR\ahistory\"\x9f\x01\n" +
	"\fDecideResult\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x126\n" +
	"\bdecision\x18\x02 \x01(\v2\x18.veya.worker.v1.DecisionH\x00R\bdecision\x123\n" +
	"\afailure\x18\x03 \x01(\v2\x17.veya.worker.v1.FailureH\x00R\afailureB\t\n" +
	"\aoutcome\"\xf0\x02\n" +
	"\bDecision\x120\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1c.veya.worker.v1.DecisionKindR\x04kind\x12\x17\n" +
	"\astep_id\x18\x02 \x01(\tR\x06stepId\x12\x12\n" +
	"\x04tool\x18\x03 \x01(\tR\x04tool\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x16\n" +
	"\x06output\x18\x05 \x01(\fR\x06output\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12.\n" +
	"\x05calls\x18\a \x03(\v2\x18.veya.worker.v1.ToolCallR\x05calls\x12.\n" +
	"\x04join\x18\b \x01(\v2\x1a.veya.worker.v1.JoinPolicyR\x04join\x12)\n" +
	"\x11wake_at_unix_nano\x18\t \x01(\x03R\x0ewakeAtUnixNano\x122\n" +
	"\x06signal\x18\n" +
	" \x01(\v2\x1a.veya.worker.v1.SignalWaitR\x06signal\"8\n" +
	"\bToolCall\x12\x12\n" +
	"\x04tool\x18\x01 \x01(\tR\x04tool\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"R\n" +
	"\n" +
	"JoinPolicy\x12,\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x18.veya.worker.v1.JoinKindR\x04kind\x12\x16\n" +
	"\x06quorum\x18\x02 \x01(\x05R\x06quorum\"N\n" +
	"\n" +
	"SignalWait\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12,\n" +
	"\x12deadline_unix_nano\x18\x02 \x01(\x03R\x10deadlineUnixNano\"\x8e\x01\n" +
	"\x03Run\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x02 \x01(\tR\tagentName\x12#\n" +
	"\ragent_version\x18\x03 \x01(\tR\fagentVersion\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x14\n" +
	"\x05input\x18\x05 \x01(\fR\x05input\"\xa8\x01\n" +
	"\x05Event\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x03R\x03seq\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x17\n" +
	"\astep_id\x18\x04 \x01(\tR\x06stepId\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12/\n" +
	"\x14created_at_unix_nano\x18\x06 \x01(\x03R\x11createdAtUnixNano\"\xe3\x01\n" +
	"\x0eExecuteRequest\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x12\n" +
	"\x04tool\x18\x02 \x01(\tR\x04tool\x12\x15\n" +
	"\x06run_id\x18\x03 \x01(\tR\x05runId\x12\x17\n" +
	"\atask_id\x18\x04 \x01(\tR\x06taskId\x12\x17\n" +
	"\astep_id\x18\x05 \x01(\tR\x06stepId\x12'\n" +
	"\x0fidempotency_key\x18\x06 \x01(\tR\x0eidempotencyKey\x12\x18\n" +
	"\apayload\x18\a \x01(\fR\apayload\x12\x18\n" +
	"\aattempt\x18\b \x01(\x05R\aattempt\"\x82\x01\n" +
	"\rExecuteResult\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x18\n" +
	"\x06result\x18\x02 \x01(\fH\x00R\x06result\x123\n" +
	"\afailure\x18\x03 \x01(\v2\x17.veya.worker.v1.FailureH\x00R\afailureB\t\n" +
	"\aoutcome\"o\n" +
	"\x10ReconcileRequest\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x12\n" +
	"\x04tool\x18\x02 \x01(\tR\x04tool\x12.\n" +
	"\x06effect\x18\x03 \x01(\v2\x16.veya.worker.v1.EffectR\x06effect\"\xa8\x01\n" +
	"\x0fReconcileResult\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12<\n" +
	"\n" +
	"resolution\x18\x02 \x01(\v2\x1a.veya.worker.v1.ResolutionH\x00R\n" +
	"resolution\x123\n" +
	"\afailure\x18\x03 \x01(\v2\x17.veya.worker.v1.FailureH\x00R\afailureB\t\n" +
	"\aoutcome\"\x97\x01\n" +
	"\n" +
	"Resolution\x122\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1e.veya.worker.v1.ResolutionKindR\x04kind\x12\x1a\n" +
	"\bresponse\x18\x02 \x01(\fR\bresponse\x12!\n" +
	"\fexternal_ref\x18\x03 \x01(\tR\vexternalRef\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\"\x81\x03\n" +
	"\x06Effect\x12\x1b\n" +
	"\teffect_id\x18\x01 \x01(\tR\beffectId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\tR\x06taskId\x12\x1f\n" +
	"\veffect_type\x18\x04 \x01(\tR\n" +
	"effectType\x12>\n" +
	"\feffect_class\x18\x05 \x01(\x0e2\x1b.veya.worker.v1.EffectClassR\veffectClass\x12'\n" +
	"\x0fidempotency_key\x18\x06 \x01(\tR\x0eidempotencyKey\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12!\n" +
	"\fexternal_ref\x18\b \x01(\tR\vexternalRef\x12\x18\n" +
	"\arequest\x18\t \x01(\fR\arequest\x12\x1a\n" +
	"\bresponse\x18\n" +
	" \x01(\fR\bresponse\x12/\n" +
	"\x14created_at_unix_nano\x18\v \x01(\x03R\x11createdAtUnixNano\"p\n" +
	"\aFailure\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x127\n" +
	"\tcertainty\x18\x03 \x01(\x0e2\x19.veya.worker.v1.CertaintyR\tcertainty*K\n" +
	"\x0fProtocolVersion\x12 \n" +
	"\x1cPROTOCOL_VERSION_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12PROTOCOL_VERSION_1\x10\x01*\xa3\x01\n" +
	"\vEffectClass\x12\x1c\n" +
	"\x18EFFECT_CLASS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11EFFECT_CLASS_NONE\x10\x01\x12\"\n" +
	"\x1eEFFECT_CLASS_IDEMPOTENT_BY_KEY\x10\x02\x12\x1a\n" +
	"\x16EFFECT_CLASS_QUERYABLE\x10\x03\x12\x1f\n" +
	"\x1bEFFECT_CLASS_UNRECONCILABLE\x10\x04*a\n" +
	"\bJoinKind\x12\x19\n" +
	"\x15JOIN_KIND_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rJOIN_KIND_ALL\x10\x01\x12\x11\n" +
	"\rJOIN_KIND_ANY\x10\x02\x12\x14\n" +
	"\x10JOIN_KIND_QUORUM\x10\x03*\x98\x02\n" +
	"\fDecisionKind\x12\x1d\n" +
	"\x19DECISION_KIND_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17DECISION_KIND_CALL_TOOL\x10\x01\x12\x1a\n" +
	"\x16DECISION_KIND_COMPLETE\x10\x02\x12\x16\n" +
	"\x12DECISION_KIND_FAIL\x10\x03\x12$\n" +
	" DECISION_KIND_CALL_TOOL_PARALLEL\x10\x04\x12\x17\n" +
	"\x13DECISION_KIND_SLEEP\x10\x05\x12!\n" +
	"\x1dDECISION_KIND_WAIT_FOR_SIGNAL\x10\x06\x12\x18\n" +
	"\x14DECISION_KIND_CANCEL\x10\a\x12\x1c\n" +
	"\x18DECISION_KIND_COMPENSATE\x10\b*\x95\x01\n" +
	"\x0eResolutionKind\x12\x1f\n" +
	"\x1bRESOLUTION_KIND_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19RESOLUTION_KIND_COMMITTED\x10\x01\x12 \n" +
	"\x1cRESOLUTION_KIND_NOT_EXECUTED\x10\x02\x12!\n" +
	"\x1dRESOLUTION_KIND_STILL_UNKNOWN\x10\x03*Y\n" +
	"\tCertainty\x12\x19\n" +
	"\x15CERTAINTY_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16CERTAINTY_NOT_EXECUTED\x10\x01\x12\x15\n" +
	"\x11CERTAINTY_UNKNOWN\x10\x022U\n" +
	"\x06Worker\x12K\n" +
	"\aSession\x12\x1d.veya.worker.v1.ClientMessage\x1a\x1d.veya.worker.v1.ServerMessage(\x010\x01B@Z>github.com/SanthoshRaaj-KR/Veya/internal/sdk/workerpb;workerpbb\x06proto3"

var (
	file_veya_worker_v1_worker_proto_rawDescOnce sync.Once
	file_veya_worker_v1_worker_proto_rawDescData []byte
)

func file_veya_worker_v1_worker_proto_rawDescGZIP() []byte {
	file_veya_worker_v1_worker_proto_rawDescOnce.Do(func() {
		file_veya_worker_v1_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_veya_worker_v1_worker_proto_rawDesc), len(file_veya_worker_v1_worker_proto_rawDesc)))
	})
	return file_veya_worker_v1_worker_proto_rawDescData
}

var file_veya_worker_v1_worker_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_veya_worker_v1_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_veya_worker_v1_worker_proto_goTypes = []any{
	(ProtocolVersion)(0),     // 0: veya.worker.v1.ProtocolVersion
	(EffectClass)(0),         // 1: veya.worker.v1.EffectClass
	(JoinKind)(0),            // 2: veya.worker.v1.JoinKind
	(DecisionKind)(0),        // 3: veya.worker.v1.DecisionKind
	(ResolutionKind)(0),      // 4: veya.worker.v1.ResolutionKind
	(Certainty)(0),           // 5: veya.worker.v1.Certainty
	(*ClientMessage)(nil),    // 6: veya.worker.v1.ClientMessage
	(*ServerMessage)(nil),    // 7: veya.worker.v1.ServerMessage
	(*Register)(nil),         // 8: veya.worker.v1.Register
	(*Registered)(nil),       // 9: veya.worker.v1.Registered
	(*ToolDescriptor)(nil),   // 10: veya.worker.v1.ToolDescriptor
	(*DecideRequest)(nil),    // 11: veya.worker.v1.DecideRequest
	(*DecideResult)(nil),     // 12: veya.worker.v1.DecideResult
	(*Decision)(nil),         // 13: veya.worker.v1.Decision
	(*ToolCall)(nil),         // 14: veya.worker.v1.ToolCall
	(*JoinPolicy)(nil),       // 15: veya.worker.v1.JoinPolicy
	(*SignalWait)(nil),       // 16: veya.worker.v1.SignalWait
	(*Run)(nil),              // 17: veya.worker.v1.Run
	(*Event)(nil),            // 18: veya.worker.v1.Event
	(*ExecuteRequest)(nil),   // 19: veya.worker.v1.ExecuteRequest
	(*ExecuteResult)(nil),    // 20: veya.worker.v1.ExecuteResult
	(*ReconcileRequest)(nil), // 21: veya.worker.v1.ReconcileRequest
	(*ReconcileResult)(nil),  // 22: veya.worker.v1.ReconcileResult
	(*Resolution)(nil),       // 23: veya.worker.v1.Resolution
	(*Effect)(nil),           // 24: veya.worker.v1.Effect
	(*Failure)(nil),          // 25: veya.worker.v1.Failure
}
var file_veya_worker_v1_worker_proto_depIdxs = []int32{
	8,  // 0: veya.worker.v1.ClientMessage.register:type_name -> veya.worker.v1.Register
	12, // 1: veya.worker.v1.ClientMessage.decide_result:type_name -> veya.worker.v1.DecideResult
	20, // 2: veya.worker.v1.ClientMessage.execute_result:type_name -> veya.worker.v1.ExecuteResult
	22, // 3: veya.worker.v1.ClientMessage.reconcile_result:type_name -> veya.worker.v1.ReconcileResult
	9,  // 4: veya.worker.v1.ServerMessage.registered:type_name -> veya.worker.v1.Registered
	11, // 5: veya.worker.v1.ServerMessage.decide:type_name -> veya.worker.v1.DecideRequest
	19, // 6: veya.worker.v1.ServerMessage.execute:type_name -> veya.worker.v1.ExecuteRequest
	21, // 7: veya.worker.v1.ServerMessage.reconcile:type_name -> veya.worker.v1.ReconcileRequest
	0,  // 8: veya.worker.v1.Register.protocol_version:type_name -> veya.worker.v1.ProtocolVersion
	10, // 9: veya.worker.v1.Register.tools:type_name -> veya.worker.v1.ToolDescriptor
	1,  // 10: veya.worker.v1.ToolDescriptor.effect_class:type_name -> veya.worker.v1.EffectClass
	17, // 11: veya.worker.v1.DecideRequest.run:type_name -> veya.worker.v1.Run
	18, // 12: veya.worker.v1.DecideRequest.history:type_name -> veya.worker.v1.Event
	13, // 13: veya.worker.v1.DecideResult.decision:type_name -> veya.worker.v1.Decision
	25, // 14: veya.worker.v1.DecideResult.failure:type_name -> veya.worker.v1.Failure
	3,  // 15: veya.worker.v1.Decision.kind:type_name -> veya.worker.v1.DecisionKind
	14, // 16: veya.worker.v1.Decision.calls:type_name -> veya.worker.v1.ToolCall
	15, // 17: veya.worker.v1.Decision.join:type_name -> veya.worker.v1.JoinPolicy
	16, // 18: veya.worker.v1.Decision.signal:type_name -> veya.worker.v1.SignalWait
	2,  // 19: veya.worker.v1.JoinPolicy.kind:type_name -> veya.worker.v1.JoinKind
	25, // 20: veya.worker.v1.ExecuteResult.failure:type_name -> veya.worker.v1.Failure
	24, // 21: veya.worker.v1.ReconcileRequest.effect:type_name -> veya.worker.v1.Effect
	23, // 22: veya.worker.v1.ReconcileResult.resolution:type_name -> veya.worker.v1.Resolution
	25, // 23: veya.worker.v1.ReconcileResult.failure:type_name -> veya.worker.v1.Failure
	4,  // 24: veya.worker.v1.Resolution.kind:type_name -> veya.worker.v1.ResolutionKind
	1,  // 25: veya.worker.v1.Effect.effect_class:type_name -> veya.worker.v1.EffectClass
	5,  // 26: veya.worker.v1.Failure.certainty:type_name -> veya.worker.v1.Certainty
	6,  // 27: veya.worker.v1.Worker.Session:input_type -> veya.worker.v1.ClientMessage
	7,  // 28: veya.worker.v1.Worker.Session:output_type -> veya.worker.v1.ServerMessage
	28, // [28:29] is the sub-list for method output_type
	27, // [27:28] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_veya_worker_v1_worker_proto_init() }
func file_veya_worker_v1_worker_proto_init() {
	if File_veya_worker_v1_worker_proto != nil {
		return
	}
	file_veya_worker_v1_worker_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientMessage_Register)(nil),
		(*ClientMessage_DecideResult)(nil),
		(*ClientMessage_ExecuteResult)(nil),
		(*ClientMessage_ReconcileResult)(nil),
	}
	file_veya_worker_v1_worker_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerMessage_Registered)(nil),
		(*ServerMessage_Decide)(nil),
		(*ServerMessage_Execute)(nil),
		(*ServerMessage_Reconcile)(nil),
	}
	file_veya_worker_v1_worker_proto_msgTypes[6].OneofWrappers = []any{
		(*DecideResult_Decision)(nil),
		(*DecideResult_Failure)(nil),
	}
	file_veya_worker_v1_worker_proto_msgTypes[14].OneofWrappers = []any{
		(*ExecuteResult_Result)(nil),
		(*ExecuteResult_Failure)(nil),
	}
	file_veya_worker_v1_worker_proto_msgTypes[16].OneofWrappers = []any{
		(*ReconcileResult_Resolution)(nil),
		(*ReconcileResult_Failure)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_veya_worker_v1_worker_proto_rawDesc), len(file_veya_worker_v1_worker_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_veya_worker_v1_worker_proto_goTypes,
		DependencyIndexes: file_veya_worker_v1_worker_proto_depIdxs,
		EnumInfos:         file_veya_worker_v1_worker_proto_enumTypes,
		MessageInfos:      file_veya_worker_v1_worker_proto_msgTypes,
	}.Build()
	File_veya_worker_v1_worker_proto = out.File
	file_veya_worker_v1_worker_proto_goTypes = nil
	file_veya_worker_v1_worker_proto_depIdxs = nil
}
