// The Veya worker protocol: the wire boundary between the Go runtime and a
// worker written in another language.
//
// This is a public contract from its first commit. Field numbers are never
// reused, fields are never removed, and a breaking change is a new package
// (veya.worker.v2) rather than an edit here.
//
// The reasoning behind the shape is in docs/worker-protocol.md. The short
// version: the client dials the runtime and opens one bidirectional stream,
// then the *server* makes requests down it and the client answers. That is
// backwards from how gRPC usually reads, and it is why a worker needs no
// inbound port, no DNS name and no certificate.
//
// What crosses this boundary is behaviour, never correctness. The claim loop,
// the lease, the fencing token and the effect ledger's reserve-commit-act
// ordering all stay on the Go side. A worker is handed a tool call that
// already has a committed ledger row behind it and an idempotency key in hand,
// and is asked only to perform it.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: veya/worker/v1/worker.proto

package workerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Worker_Session_FullMethodName = "/veya.worker.v1.Worker/Session"
)

// WorkerClient is the client API for Worker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Worker is the whole protocol.
type WorkerClient interface {
	// Session is opened by the worker and lives as long as the worker does.
	//
	// The stream is the registration. When it drops, every tool it registered
	// is gone and the runtime knows at once, rather than finding out on the
	// next call to an address nobody is listening on.
	Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerMessage], error)
}

type workerClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerClient(cc grpc.ClientConnInterface) WorkerClient {
	return &workerClient{cc}
}

func (c *workerClient) Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Worker_ServiceDesc.Streams[0], Worker_Session_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientMessage, ServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Worker_SessionClient = grpc.BidiStreamingClient[ClientMessage, ServerMessage]

// WorkerServer is the server API for Worker service.
// All implementations must embed UnimplementedWorkerServer
// for forward compatibility.
//
// Worker is the whole protocol.
type WorkerServer interface {
	// Session is opened by the worker and lives as long as the worker does.
	//
	// The stream is the registration. When it drops, every tool it registered
	// is gone and the runtime knows at once, rather than finding out on the
	// next call to an address nobody is listening on.
	Session(grpc.BidiStreamingServer[ClientMessage, ServerMessage]) error
	mustEmbedUnimplementedWorkerServer()
}

// UnimplementedWorkerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkerServer struct{}

func (UnimplementedWorkerServer) Session(grpc.BidiStreamingServer[ClientMessage, ServerMessage]) error {
	return status.Error(codes.Unimplemented, "method Session not implemented")
}
func (UnimplementedWorkerServer) mustEmbedUnimplementedWorkerServer() {}
func (UnimplementedWorkerServer) testEmbeddedByValue()                {}

// UnsafeWorkerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerServer will
// result in compilation errors.
type UnsafeWorkerServer interface {
	mustEmbedUnimplementedWorkerServer()
}

func RegisterWorkerServer(s grpc.ServiceRegistrar, srv WorkerServer) {
	// If the following call panics, it indicates UnimplementedWorkerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Worker_ServiceDesc, srv)
}

func _Worker_Session_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WorkerServer).Session(&grpc.GenericServerStream[ClientMessage, ServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Worker_SessionServer = grpc.BidiStreamingServer[ClientMessage, ServerMessage]

// Worker_ServiceDesc is the grpc.ServiceDesc for Worker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Worker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "veya.worker.v1.Worker",
	HandlerType: (*WorkerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Session",
			Handler:       _Worker_Session_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "veya/worker/v1/worker.proto",
}
