# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from veya.worker.v1 import worker_pb2 as veya_dot_worker_dot_v1_dot_worker__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in veya/worker/v1/worker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkerStub:
    """Worker is the whole protocol.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Session = channel.stream_stream(
                '/veya.worker.v1.Worker/Session',
                request_serializer=veya_dot_worker_dot_v1_dot_worker__pb2.ClientMessage.SerializeToString,
                response_deserializer=veya_dot_worker_dot_v1_dot_worker__pb2.ServerMessage.FromString,
                _registered_method=True)


class WorkerServicer:
    """Worker is the whole protocol.
    """

    def Session(self, request_iterator, context):
        """Session is opened by the worker and lives as long as the worker does.

        The stream is the registration. When it drops, every tool it registered
        is gone and the runtime knows at once, rather than finding out on the
        next call to an address nobody is listening on.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Session': grpc.stream_stream_rpc_method_handler(
                    servicer.Session,
                    request_deserializer=veya_dot_worker_dot_v1_dot_worker__pb2.ClientMessage.FromString,
                    response_serializer=veya_dot_worker_dot_v1_dot_worker__pb2.ServerMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'veya.worker.v1.Worker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('veya.worker.v1.Worker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Worker:
    """Worker is the whole protocol.
    """

    @staticmethod
    def Session(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/veya.worker.v1.Worker/Session',
            veya_dot_worker_dot_v1_dot_worker__pb2.ClientMessage.SerializeToString,
            veya_dot_worker_dot_v1_dot_worker__pb2.ServerMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
